# Generated by Django 5.1.4 on 2024-12-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_profile_user_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="user_color",
            field=models.CharField(default="(223,118,203,.3)", max_length=100),
        ),
    ]
