# Generated by Django 5.2 on 2025-04-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_user_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_color',
            field=models.CharField(default='(217,245,129,.3)', max_length=100),
        ),
    ]
