# Generated by Django 3.1.3 on 2021-01-29 06:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_issued_date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'ordering': ['-report_issued_date'],
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_notes', models.TextField(verbose_name='Issues/Notes')),
                ('action_action', models.TextField(verbose_name='Actions')),
                ('action_date_deadline', models.DateField(verbose_name='Date')),
                ('action_assignees', models.ManyToManyField(related_name='user_report_actions', to=settings.AUTH_USER_MODEL, verbose_name='Persons')),
                ('action_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reports', to=settings.AUTH_USER_MODEL)),
                ('action_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_reports', to='projects.project')),
                ('action_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_actions', to='reports.report')),
            ],
            options={
                'ordering': ['-action_report'],
            },
        ),
    ]
