# Generated by Django 3.1.3 on 2021-01-31 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_issued_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Report date'),
        ),
    ]
